package frc.robot.commands;
import java.util.function.Supplier;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Ramp;

public class AutoRampCmd extends CommandBase {
        private final Ramp m_Ramp;
        private final Double rampSpeed;
        double startTime = Timer.getFPGATimestamp();
        double elapsedTime;

    public AutoRampCmd(Ramp subsystem, Double rampSpeed){
        this.rampSpeed = rampSpeed;

        

        m_Ramp = subsystem;
        addRequirements(m_Ramp);
    }



    @Override
    public void initialize(){
       // System.out.println("AutoRamp starting");
    }
    @Override
    public void execute(){
        double currentTime =Timer.getFPGATimestamp();
        elapsedTime = currentTime - startTime;

        if (elapsedTime > 0.75){
                m_Ramp.convey(-rampSpeed);
        }
      
        
    }
     // Called once the command ends or is interrupted.
     @Override
     public void end(boolean interrupted) {
        // System.out.println("Auto Ramp has ended");
         m_Ramp.convey(0.0);
 
     }
 
     // Returns true when the command should end.
     @Override
     public boolean isFinished() {
         if (elapsedTime < 4.0){
            return false;
         }
         else{
            m_Ramp.convey(0.0);
            return true;
         }
         
     }
 
     @Override
     public boolean runsWhenDisabled() {
         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
         return false;
 
     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
     }
 
 

}
