package frc.robot.commands;
import java.util.function.Supplier;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Launcher;

public class AutoLauncherCmd extends CommandBase {
        private final Launcher m_launcher;
        private final Double launchSpeed;
        double startTime =Timer.getFPGATimestamp();
        double elapsedTime;

    

    public AutoLauncherCmd(Launcher subsystem, Double launchSpeed){
        this.launchSpeed = launchSpeed;

        

        m_launcher = subsystem;
        addRequirements(m_launcher);
    }



    @Override
    public void initialize(){
       // System.out.println("Launcher starting");
    }
    @Override
    public void execute(){


        
        

        
        m_launcher.spin(launchSpeed);
        
   
    }
     // Called once the command ends or is interrupted.
     @Override
     public void end(boolean interrupted) {
        // System.out.println("Launch");
         m_launcher.spin(0.0);
 
     }
 
     // Returns true when the command should end.
     @Override
     public boolean isFinished() {
        double currentTime =Timer.getFPGATimestamp();
        elapsedTime = currentTime - startTime;
        
        if (elapsedTime < 4.0){
            return false;
         }
         else{
            m_launcher.spin(0.0);
            return true;
         }
     }
 
     @Override
     public boolean runsWhenDisabled() {
         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
         return false;
 
     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
     }
 
 

}