package frc.robot.commands;
import java.util.function.Supplier;


import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Elevator;


public class ElevatorCmd extends CommandBase {
        private final Elevator m_elevator;
        private final Double actuatorSpeed;


    public ElevatorCmd(Elevator subsystem, Double actuatorSpeed){
        this.actuatorSpeed = actuatorSpeed;

        

        m_elevator = subsystem;
        addRequirements(m_elevator);
    }



    @Override
    public void initialize(){
        System.out.println("Elevator Moving");
    }
    @Override
    public void execute(){


        m_elevator.left(actuatorSpeed);
        
    }
     // Called once the command ends or is interrupted.
     @Override
     public void end(boolean interrupted) {
        
         m_elevator.left(0.0);
 
     }
 
     // Returns true when the command should end.
     @Override
     public boolean isFinished() {
         return false;
     }
 
     @Override
     public boolean runsWhenDisabled() {
         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
         return false;
 
     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
     }
 
 

}