package frc.robot.commands;
import java.util.function.Supplier;


import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Intake;

public class IntakeCmd extends CommandBase {
        private final Intake m_intake;
        private final Double launchSpeed;


    public IntakeCmd(Intake subsystem, Double launchSpeed){
        this.launchSpeed = launchSpeed;

        

        m_intake = subsystem;
        addRequirements(m_intake);
    }



    @Override
    public void initialize(){
        
    }
    @Override
    public void execute(){


        m_intake.spin(launchSpeed);
        
    }
     // Called once the command ends or is interrupted.
     @Override
     public void end(boolean interrupted) {
         m_intake.spin(0.0);
 
     }
 
     // Returns true when the command should end.
     @Override
     public boolean isFinished() {
         return false;
     }
 
     @Override
     public boolean runsWhenDisabled() {
         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
         return false;
 
     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
     }
 
 

}