// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import java.util.function.Supplier;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Tankdrive extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final DriveTrain m_driveTrain;
        private boolean reverseControls;
        private final Supplier<Double> leftSpeedFunction, rightSpeedFunction;
        private RobotContainer m_RobotContainer;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    /*public Tankdrive(DriveTrain subsystem, Supplier<Double> leftSpeedFunction, Supplier<Double> rightSpeedFunction, RobotContainer m_RobotContainer, boolean reverseControls) {
        this(subsystem,leftSpeedFunction,rightSpeedFunction, m_RobotContainer);
        reverseControls = true;



    }*/

    public Tankdrive(DriveTrain subsystem, Supplier<Double> leftSpeedFunction, Supplier<Double> rightSpeedFunction, RobotContainer m_RobotContainer) {
        this.leftSpeedFunction = leftSpeedFunction;
        this.rightSpeedFunction = rightSpeedFunction;
       // reverseControls = false;
        this.m_RobotContainer = m_RobotContainer;
        
            


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        addRequirements(m_driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        System.out.println("initializing tank drive");
        
        
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        double temp;
        double left = leftSpeedFunction.get();
        double right = rightSpeedFunction.get();

        if (m_RobotContainer.getRightStick().getThrottle() >= 0.0){
            reverseControls = false;

        } else{
            reverseControls = true;
        }


        if (reverseControls == true){
            temp = left;
            left = -right;
            right = -temp;
        }

       System.out.println(m_driveTrain.getLeftEncoder()+ "\t\t"+m_driveTrain.getRightEncoder() );
        
        m_driveTrain.drive(left,right);
        

        //Reverse code
        

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        System.out.println("You've reached the end");
        System.out.println(leftSpeedFunction);
        System.out.println(rightSpeedFunction);



    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
